ENG-177836: Update office show and index endpoint doc
ananya-ramamurthy/moxiworks-platform.github.io pull request #1
Opened 2024-06-12 03:34 UTC by ananya-ramamurthy

- Updated offices show and index to include company_programs attributes

2024-06-12 15:49 UTC, badran047 commented on source/partials/public_api/api_usage/office/index.md.erb
> +<span class="response-data-remarks">A list of the company specific program names in which the agent participates or is a member.</span>
Because this is on the office entity, should this say (same below):
`...agent's office...`

2024-06-12 15:51 UTC, badran047 requested changes
Because this is on the office entity, should it say:
`...agent's office...`

2024-06-12 23:50 UTC, ananya-ramamurthy commented
> Because this is on the office entity, should it say: `...agent's office...`

Maybe a question to @rjoehatfield. I've just copied the text from JIRA ticket https://moxiworks.atlassian.net/browse/ENG-177836

2024-06-13 14:23 UTC, badran047 commented
> > Because this is on the office entity, should it say: `...agent's office...`
> 
> Maybe a question to @rjoehatfield. I've just copied the text from JIRA ticket https://moxiworks.atlassian.net/browse/ENG-177836

@ananya-ramamurthy I think that was just copied from the agent entity ([here](https://github.com/moxiworks-platform/moxiworks-platform.github.io/blob/330fc2fc4b5ff34630ac86d221de2d26b73956bb/source/partials/public_api/api_usage/agent/index.md.erb#L638))

2024-06-17 03:02 UTC, ananya-ramamurthy commented
> > > Because this is on the office entity, should it say: `...agent's office...`
> > 
> > 
> > Maybe a question to @rjoehatfield. I've just copied the text from JIRA ticket https://moxiworks.atlassian.net/browse/ENG-177836
> 
> @ananya-ramamurthy I think that was just copied from the agent entity ([here](https://github.com/moxiworks-platform/moxiworks-platform.github.io/blob/330fc2fc4b5ff34630ac86d221de2d26b73956bb/source/partials/public_api/api_usage/agent/index.md.erb#L638))

Makes sense. I've updated that. Thank you

2024-06-17 15:59 UTC, badran047 approved these changes

2024-06-18 00:08 UTC, rjoehatfield approved these changes

2024-06-20 05:09 UTC, merged